### PR TITLE
Update py_demo.py

### PR DESCRIPTION
**Pull request by saiprabhakar**
Changed the Caffe root folder path.

### CODE REVIEW

**Comment by gcucurull** [comment]
Hey, thank you for the fix, I totally had forgotten about the path to Caffe, it is harcoded to my machine's path. It definitely needs to be fixed, but I think that it would be better to change it to something like "'/PATH/TO/CAFFE/'" instead of "../caffe", because although the latter is better than the current path, it is still a relative path which works only in certain cases.

What do you think?

**Comment by saiprabhakar** [comment]
Hi,
I think you can make it "'/PATH/TO/CAFFE/'", and mention it as an instruction in your Readme file, or we extract caffe path from bash file. I think the second option is better. We just have to use "import os" "caffe_root = os.environ['CAFFE_ROOT'] + '/' ". This is ofcourse assuming the user have defined the caffe path in their bashrc as instructed in the caffe repo.

Which one do you like.

**Comment by gcucurull** [comment]
Ok, I like the second idea, with and Exception for users who have not defined the caffe path. It is very elegant, thanks!

**Comment by saiprabhakar** [comment]
I made those changes

**Comment by gcucurull** [comment]
Awesome! Thank you very much!

**Pull request merged**
